services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: exchangerate-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
    healthcheck:
      test: [
        "CMD-SHELL",
        "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P \"$SA_PASSWORD\" -Q \"SELECT 1\" || exit 1"
      ]
      interval: 5s
      retries: 20
      start_period: 5s
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: src/ExchangeRateService/Dockerfile
      target: dev
    container_name: exchangerate-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${CONNECTION_STRING}
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
    volumes:
      - ./src/ExchangeRateService:/workspace
      - exchangerate_obj:/workspace/obj

    develop:
      watch:
        - action: rebuild
          path: ./src/ExchangeRateService/Dockerfile
          ignore:
            - bin/
            - obj/
    command: ["dotnet", "watch", "run", "--project", "ExchangeRateService.csproj", "--urls=http://0.0.0.0:8080"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  sql_data:
  exchangerate_obj:
